///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f23282ac-99c3-408b-a54d-cd2ce5a2329a")]
    public partial class MyTestRepository : RepoGenBaseFolder
    {
        static MyTestRepository instance = new MyTestRepository();
        MyTestRepositoryFolders.GEOTECH3D9118616917X64ДемонстраAppFolder _geotech3d9118616917x64демонстра;
        MyTestRepositoryFolders.GeoTech3DAppFolder _geotech3d;
        MyTestRepositoryFolders.GeotechDemoAppFolder _geotechdemo;
        MyTestRepositoryFolders.GeoTech3D1AppFolder _geotech3d1;

        /// <summary>
        /// Gets the singleton class instance representing the MyTestRepository element repository.
        /// </summary>
        [RepositoryFolder("f23282ac-99c3-408b-a54d-cd2ce5a2329a")]
        public static MyTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTestRepository() 
            : base("MyTestRepository", "/", null, 0, false, "f23282ac-99c3-408b-a54d-cd2ce5a2329a", ".\\RepositoryImages\\MyTestRepositoryf23282ac.rximgres")
        {
            _geotech3d9118616917x64демонстра = new MyTestRepositoryFolders.GEOTECH3D9118616917X64ДемонстраAppFolder(this);
            _geotech3d = new MyTestRepositoryFolders.GeoTech3DAppFolder(this);
            _geotechdemo = new MyTestRepositoryFolders.GeotechDemoAppFolder(this);
            _geotech3d1 = new MyTestRepositoryFolders.GeoTech3D1AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f23282ac-99c3-408b-a54d-cd2ce5a2329a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The GEOTECH3D9118616917X64Демонстра folder.
        /// </summary>
        [RepositoryFolder("3595640e-61bc-4127-a59f-6ac7b7064f79")]
        public virtual MyTestRepositoryFolders.GEOTECH3D9118616917X64ДемонстраAppFolder GEOTECH3D9118616917X64Демонстра
        {
            get { return _geotech3d9118616917x64демонстра; }
        }

        /// <summary>
        /// The GeoTech3D folder.
        /// </summary>
        [RepositoryFolder("2413aec0-25a5-4c31-93c5-6d7114eddbd4")]
        public virtual MyTestRepositoryFolders.GeoTech3DAppFolder GeoTech3D
        {
            get { return _geotech3d; }
        }

        /// <summary>
        /// The GeotechDemo folder.
        /// </summary>
        [RepositoryFolder("88774cfd-4c72-4fdf-a86a-abf80c430404")]
        public virtual MyTestRepositoryFolders.GeotechDemoAppFolder GeotechDemo
        {
            get { return _geotechdemo; }
        }

        /// <summary>
        /// The GeoTech3D1 folder.
        /// </summary>
        [RepositoryFolder("c7553724-e8ac-42cb-8933-f5a1c41d0403")]
        public virtual MyTestRepositoryFolders.GeoTech3D1AppFolder GeoTech3D1
        {
            get { return _geotech3d1; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTestRepositoryFolders
    {
        /// <summary>
        /// The GEOTECH3D9118616917X64ДемонстраAppFolder folder.
        /// </summary>
        [RepositoryFolder("3595640e-61bc-4127-a59f-6ac7b7064f79")]
        public partial class GEOTECH3D9118616917X64ДемонстраAppFolder : RepoGenBaseFolder
        {
            MyTestRepositoryFolders.Form65280Folder _form65280;
            RepoItemInfo _openInfo;
            RepoItemInfo _геологияInfo;
            RepoItemInfo _treeitem1113410Info;
            RepoItemInfo _menuitemразрезInfo;
            RepoItemInfo _подземныегорныеработыфрагментInfo;

            /// <summary>
            /// Creates a new GEOTECH3D9118616917X64Демонстра  folder.
            /// </summary>
            public GEOTECH3D9118616917X64ДемонстраAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D9118616917X64Демонстра", "/form[@name='MainForm']", parentFolder, 30000, null, true, "3595640e-61bc-4127-a59f-6ac7b7064f79", "")
            {
                _form65280 = new MyTestRepositoryFolders.Form65280Folder(this);
                _openInfo = new RepoItemInfo(this, "Open", "?/?/form[@title='Стандартные']/element[1]", "?/?/form[@title='Стандартные']/element[1]", 30000, null, "0d8fbafc-22bc-4829-a1bf-adca1a252913");
                _геологияInfo = new RepoItemInfo(this, "Геология", "container[@name='LeftDockPanel']/form[@name='OKBottomDlg']/?/?/container[@name='ObjectsTabSh']//tree[@name='ObjTree']/?/?/treeitem[@name='Геология']", ".//treeitem[@name='Геология']", 30000, null, "a944214d-7673-464b-a1b8-00efa36dd6cc");
                _treeitem1113410Info = new RepoItemInfo(this, "TreeItem1113410", "container[@name='LeftDockPanel']/form[@name='OKBottomDlg']/?/?/container[@name='ObjectsTabSh']//tree[@name='ObjTree']//treeitem[@name='11_13 _410']", ".//treeitem[@name='11_13 _410']", 30000, null, "43436062-1a1c-4d81-b102-9051fbd6c425");
                _menuitemразрезInfo = new RepoItemInfo(this, "MenuItemРазрез", "?/?/menuitem[@name='RazrezItem']", "?/?/menuitem[@name='RazrezItem']", 30000, null, "fea63b8f-ee5c-448a-a1b1-5769e3871893");
                _подземныегорныеработыфрагментInfo = new RepoItemInfo(this, "ПодземныеГорныеРаботыФрагмент", "form[@name='MDIChild']//listitem[@name>'Подземные горные работы (']", ".//listitem[@name>'Подземные горные работы (']", 30000, null, "933c5ab9-4a7f-47f9-9e53-deae5f91f5ac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3595640e-61bc-4127-a59f-6ac7b7064f79")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3595640e-61bc-4127-a59f-6ac7b7064f79")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Open item.
            /// </summary>
            [RepositoryItem("0d8fbafc-22bc-4829-a1bf-adca1a252913")]
            public virtual Ranorex.Unknown Open
            {
                get
                {
                    return _openInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Open item info.
            /// </summary>
            [RepositoryItemInfo("0d8fbafc-22bc-4829-a1bf-adca1a252913")]
            public virtual RepoItemInfo OpenInfo
            {
                get
                {
                    return _openInfo;
                }
            }

            /// <summary>
            /// The Геология item.
            /// </summary>
            [RepositoryItem("a944214d-7673-464b-a1b8-00efa36dd6cc")]
            public virtual Ranorex.TreeItem Геология
            {
                get
                {
                    return _геологияInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Геология item info.
            /// </summary>
            [RepositoryItemInfo("a944214d-7673-464b-a1b8-00efa36dd6cc")]
            public virtual RepoItemInfo ГеологияInfo
            {
                get
                {
                    return _геологияInfo;
                }
            }

            /// <summary>
            /// The TreeItem1113410 item.
            /// </summary>
            [RepositoryItem("43436062-1a1c-4d81-b102-9051fbd6c425")]
            public virtual Ranorex.TreeItem TreeItem1113410
            {
                get
                {
                    return _treeitem1113410Info.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The TreeItem1113410 item info.
            /// </summary>
            [RepositoryItemInfo("43436062-1a1c-4d81-b102-9051fbd6c425")]
            public virtual RepoItemInfo TreeItem1113410Info
            {
                get
                {
                    return _treeitem1113410Info;
                }
            }

            /// <summary>
            /// The MenuItemРазрез item.
            /// </summary>
            [RepositoryItem("fea63b8f-ee5c-448a-a1b1-5769e3871893")]
            public virtual Ranorex.MenuItem MenuItemРазрез
            {
                get
                {
                    return _menuitemразрезInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemРазрез item info.
            /// </summary>
            [RepositoryItemInfo("fea63b8f-ee5c-448a-a1b1-5769e3871893")]
            public virtual RepoItemInfo MenuItemРазрезInfo
            {
                get
                {
                    return _menuitemразрезInfo;
                }
            }

            /// <summary>
            /// The ПодземныеГорныеРаботыФрагмент item.
            /// </summary>
            [RepositoryItem("933c5ab9-4a7f-47f9-9e53-deae5f91f5ac")]
            public virtual Ranorex.ListItem ПодземныеГорныеРаботыФрагмент
            {
                get
                {
                    return _подземныегорныеработыфрагментInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ПодземныеГорныеРаботыФрагмент item info.
            /// </summary>
            [RepositoryItemInfo("933c5ab9-4a7f-47f9-9e53-deae5f91f5ac")]
            public virtual RepoItemInfo ПодземныеГорныеРаботыФрагментInfo
            {
                get
                {
                    return _подземныегорныеработыфрагментInfo;
                }
            }

            /// <summary>
            /// The Form65280 folder.
            /// </summary>
            [RepositoryFolder("9973f433-d0a4-42ae-8c97-2c22ab323647")]
            public virtual MyTestRepositoryFolders.Form65280Folder Form65280
            {
                get { return _form65280; }
            }
        }

        /// <summary>
        /// The Form65280Folder folder.
        /// </summary>
        [RepositoryFolder("9973f433-d0a4-42ae-8c97-2c22ab323647")]
        public partial class Form65280Folder : RepoGenBaseFolder
        {
            RepoItemInfo _z500000Info;
            RepoItemInfo _м100000Info;
            RepoItemInfo _р6plus44000Info;
            RepoItemInfo _планInfo;
            RepoItemInfo _сеч1Info;

            /// <summary>
            /// Creates a new Form65280  folder.
            /// </summary>
            public Form65280Folder(RepoGenBaseFolder parentFolder) :
                    base("Form65280", "form[@name='MDIChild']", parentFolder, 30000, null, false, "9973f433-d0a4-42ae-8c97-2c22ab323647", "")
            {
                _z500000Info = new RepoItemInfo(this, "Z500000", ".//listitem[@name='Z: 500.000']", "listitem[@name='Z: 500.000']", 30000, null, "fee3fb1f-46ec-4928-b67c-3167cfd9d757");
                _м100000Info = new RepoItemInfo(this, "М100000", ".//listitem[@name='М 100.000']", "listitem[@name='М 100.000']", 30000, null, "a0e8262f-86cd-4072-9230-d3de29cff799");
                _р6plus44000Info = new RepoItemInfo(this, "Р6Plus44000", ".//listitem[@name='Р 6+44.000']", "listitem[@name='Р 6+44.000']", 30000, null, "6707e571-54de-46c2-a9d8-306e9074e376");
                _планInfo = new RepoItemInfo(this, "План", ".//listitem[@name='План']", "listitem[@name='План']", 30000, null, "dcc8c09a-8450-419c-ac6f-e0f8b3fc2dd1");
                _сеч1Info = new RepoItemInfo(this, "Сеч1", ".//listitem[@name='Сеч: 1']", "listitem[@name='Сеч: 1']", 30000, null, "a157615f-087d-48cb-a8fe-75b0c3cbb0b1");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9973f433-d0a4-42ae-8c97-2c22ab323647")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9973f433-d0a4-42ae-8c97-2c22ab323647")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Z500000 item.
            /// </summary>
            [RepositoryItem("fee3fb1f-46ec-4928-b67c-3167cfd9d757")]
            public virtual Ranorex.ListItem Z500000
            {
                get
                {
                    return _z500000Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Z500000 item info.
            /// </summary>
            [RepositoryItemInfo("fee3fb1f-46ec-4928-b67c-3167cfd9d757")]
            public virtual RepoItemInfo Z500000Info
            {
                get
                {
                    return _z500000Info;
                }
            }

            /// <summary>
            /// The М100000 item.
            /// </summary>
            [RepositoryItem("a0e8262f-86cd-4072-9230-d3de29cff799")]
            public virtual Ranorex.ListItem М100000
            {
                get
                {
                    return _м100000Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The М100000 item info.
            /// </summary>
            [RepositoryItemInfo("a0e8262f-86cd-4072-9230-d3de29cff799")]
            public virtual RepoItemInfo М100000Info
            {
                get
                {
                    return _м100000Info;
                }
            }

            /// <summary>
            /// The Р6Plus44000 item.
            /// </summary>
            [RepositoryItem("6707e571-54de-46c2-a9d8-306e9074e376")]
            public virtual Ranorex.ListItem Р6Plus44000
            {
                get
                {
                    return _р6plus44000Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Р6Plus44000 item info.
            /// </summary>
            [RepositoryItemInfo("6707e571-54de-46c2-a9d8-306e9074e376")]
            public virtual RepoItemInfo Р6Plus44000Info
            {
                get
                {
                    return _р6plus44000Info;
                }
            }

            /// <summary>
            /// The План item.
            /// </summary>
            [RepositoryItem("dcc8c09a-8450-419c-ac6f-e0f8b3fc2dd1")]
            public virtual Ranorex.ListItem План
            {
                get
                {
                    return _планInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The План item info.
            /// </summary>
            [RepositoryItemInfo("dcc8c09a-8450-419c-ac6f-e0f8b3fc2dd1")]
            public virtual RepoItemInfo ПланInfo
            {
                get
                {
                    return _планInfo;
                }
            }

            /// <summary>
            /// The Сеч1 item.
            /// </summary>
            [RepositoryItem("a157615f-087d-48cb-a8fe-75b0c3cbb0b1")]
            public virtual Ranorex.ListItem Сеч1
            {
                get
                {
                    return _сеч1Info.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Сеч1 item info.
            /// </summary>
            [RepositoryItemInfo("a157615f-087d-48cb-a8fe-75b0c3cbb0b1")]
            public virtual RepoItemInfo Сеч1Info
            {
                get
                {
                    return _сеч1Info;
                }
            }
        }

        /// <summary>
        /// The GeoTech3DAppFolder folder.
        /// </summary>
        [RepositoryFolder("2413aec0-25a5-4c31-93c5-6d7114eddbd4")]
        public partial class GeoTech3DAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _подземныегорныеработыфрагментInfo;
            RepoItemInfo _открытьInfo;

            /// <summary>
            /// Creates a new GeoTech3D  folder.
            /// </summary>
            public GeoTech3DAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D", "/form[@name='OpenProj']", parentFolder, 30000, null, true, "2413aec0-25a5-4c31-93c5-6d7114eddbd4", "")
            {
                _подземныегорныеработыфрагментInfo = new RepoItemInfo(this, "ПодземныеГорныеРаботыФрагмент", "?/?/listitem[@name>'Подземные горные работы (']", "?/?/listitem[@name>'Подземные горные работы (']", 30000, null, "91e9f832-769c-4157-9e36-3e4c07a99ec1");
                _открытьInfo = new RepoItemInfo(this, "Открыть", "button[@name='btnOpen']", "button[@name='btnOpen']", 30000, null, "c21ee97f-eac8-41d1-817e-b653aa087a6d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("2413aec0-25a5-4c31-93c5-6d7114eddbd4")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2413aec0-25a5-4c31-93c5-6d7114eddbd4")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ПодземныеГорныеРаботыФрагмент item.
            /// </summary>
            [RepositoryItem("91e9f832-769c-4157-9e36-3e4c07a99ec1")]
            public virtual Ranorex.ListItem ПодземныеГорныеРаботыФрагмент
            {
                get
                {
                    return _подземныегорныеработыфрагментInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ПодземныеГорныеРаботыФрагмент item info.
            /// </summary>
            [RepositoryItemInfo("91e9f832-769c-4157-9e36-3e4c07a99ec1")]
            public virtual RepoItemInfo ПодземныеГорныеРаботыФрагментInfo
            {
                get
                {
                    return _подземныегорныеработыфрагментInfo;
                }
            }

            /// <summary>
            /// The Открыть item.
            /// </summary>
            [RepositoryItem("c21ee97f-eac8-41d1-817e-b653aa087a6d")]
            public virtual Ranorex.Button Открыть
            {
                get
                {
                    return _открытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Открыть item info.
            /// </summary>
            [RepositoryItemInfo("c21ee97f-eac8-41d1-817e-b653aa087a6d")]
            public virtual RepoItemInfo ОткрытьInfo
            {
                get
                {
                    return _открытьInfo;
                }
            }
        }

        /// <summary>
        /// The GeotechDemoAppFolder folder.
        /// </summary>
        [RepositoryFolder("88774cfd-4c72-4fdf-a86a-abf80c430404")]
        public partial class GeotechDemoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _menuitemInfo;
            RepoItemInfo _формированиеразрезовInfo;
            RepoItemInfo _закрытьудалитьвсеразрезыInfo;

            /// <summary>
            /// Creates a new GeotechDemo  folder.
            /// </summary>
            public GeotechDemoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeotechDemo", "/contextmenu[@processname='Geotech_Demo']", parentFolder, 30000, null, false, "88774cfd-4c72-4fdf-a86a-abf80c430404", "")
            {
                _menuitemInfo = new RepoItemInfo(this, "MenuItem", "contextmenu/menuitem[1]", "contextmenu/menuitem[1]", 30000, null, "ac15293d-d4c7-4351-af83-403337fd1c3d");
                _формированиеразрезовInfo = new RepoItemInfo(this, "ФормированиеРазрезов", "?/?/menuitem[@accessiblename='Формирование разрезов']", "?/?/menuitem[@accessiblename='Формирование разрезов']", 30000, null, "83ed1421-92b3-4c75-92c0-43431a9db4f1");
                _закрытьудалитьвсеразрезыInfo = new RepoItemInfo(this, "ЗакрытьУдалитьВсеРазрезы", "?/?/menuitem[@accessiblename>'Закрыть/Удалить все разре']", "?/?/menuitem[@accessiblename>'Закрыть/Удалить все разре']", 30000, null, "daee5c72-377a-4933-b7fe-300b99de7d4e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("88774cfd-4c72-4fdf-a86a-abf80c430404")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("88774cfd-4c72-4fdf-a86a-abf80c430404")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The MenuItem item.
            /// </summary>
            [RepositoryItem("ac15293d-d4c7-4351-af83-403337fd1c3d")]
            public virtual Ranorex.MenuItem MenuItem
            {
                get
                {
                    return _menuitemInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItem item info.
            /// </summary>
            [RepositoryItemInfo("ac15293d-d4c7-4351-af83-403337fd1c3d")]
            public virtual RepoItemInfo MenuItemInfo
            {
                get
                {
                    return _menuitemInfo;
                }
            }

            /// <summary>
            /// The ФормированиеРазрезов item.
            /// </summary>
            [RepositoryItem("83ed1421-92b3-4c75-92c0-43431a9db4f1")]
            public virtual Ranorex.MenuItem ФормированиеРазрезов
            {
                get
                {
                    return _формированиеразрезовInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ФормированиеРазрезов item info.
            /// </summary>
            [RepositoryItemInfo("83ed1421-92b3-4c75-92c0-43431a9db4f1")]
            public virtual RepoItemInfo ФормированиеРазрезовInfo
            {
                get
                {
                    return _формированиеразрезовInfo;
                }
            }

            /// <summary>
            /// The ЗакрытьУдалитьВсеРазрезы item.
            /// </summary>
            [RepositoryItem("daee5c72-377a-4933-b7fe-300b99de7d4e")]
            public virtual Ranorex.MenuItem ЗакрытьУдалитьВсеРазрезы
            {
                get
                {
                    return _закрытьудалитьвсеразрезыInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ЗакрытьУдалитьВсеРазрезы item info.
            /// </summary>
            [RepositoryItemInfo("daee5c72-377a-4933-b7fe-300b99de7d4e")]
            public virtual RepoItemInfo ЗакрытьУдалитьВсеРазрезыInfo
            {
                get
                {
                    return _закрытьудалитьвсеразрезыInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3D1AppFolder folder.
        /// </summary>
        [RepositoryFolder("c7553724-e8ac-42cb-8933-f5a1c41d0403")]
        public partial class GeoTech3D1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _edzcoordInfo;
            RepoItemInfo _edycoordInfo;
            RepoItemInfo _edxcoordInfo;
            RepoItemInfo _вплоскостиxyInfo;
            RepoItemInfo _вплоскостиxzInfo;
            RepoItemInfo _вплоскостиyzInfo;
            RepoItemInfo _планпоxyInfo;
            RepoItemInfo _произвольныйInfo;
            RepoItemInfo _закрытьInfo;

            /// <summary>
            /// Creates a new GeoTech3D1  folder.
            /// </summary>
            public GeoTech3D1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D1", "/form[@name='frmCutCreation']", parentFolder, 30000, null, true, "c7553724-e8ac-42cb-8933-f5a1c41d0403", "")
            {
                _edzcoordInfo = new RepoItemInfo(this, "EdZCoord", "text[@name='edZCoord']", "text[@name='edZCoord']", 30000, null, "389fe77b-db42-4533-8527-75fc082e7d46");
                _edycoordInfo = new RepoItemInfo(this, "EdYCoord", "text[@name='edYCoord']", "text[@name='edYCoord']", 30000, null, "758cf676-9bea-455f-af4e-35a3faba39d1");
                _edxcoordInfo = new RepoItemInfo(this, "EdXCoord", "text[@name='edXCoord']", "text[@name='edXCoord']", 30000, null, "10bb5678-82d1-49c1-a544-9c8b5c5c29f4");
                _вплоскостиxyInfo = new RepoItemInfo(this, "ВПлоскостиXY", "button[@name='btnCutXYPlane']", "button[@name='btnCutXYPlane']", 30000, null, "c4f0ddb5-69e4-4e85-8f09-949159db1a0b");
                _вплоскостиxzInfo = new RepoItemInfo(this, "ВПлоскостиXZ", "button[@name='btnCutXZPlane']", "button[@name='btnCutXZPlane']", 30000, null, "bebbfa94-8f36-4552-b028-598c11519480");
                _вплоскостиyzInfo = new RepoItemInfo(this, "ВПлоскостиYZ", "button[@name='btnCutYZPlane']", "button[@name='btnCutYZPlane']", 30000, null, "5f4b7aca-1248-4e52-be6a-69f17d797e75");
                _планпоxyInfo = new RepoItemInfo(this, "ПланПоXY", "button[@name='btnPlaneCut']", "button[@name='btnPlaneCut']", 30000, null, "ece82c9f-c2d2-4d62-ae18-0170de7fa5d8");
                _произвольныйInfo = new RepoItemInfo(this, "Произвольный", "button[@name='btnCutByPoints']", "button[@name='btnCutByPoints']", 30000, null, "6166c0e5-b0ec-47f0-b66e-c132a8a2f83e");
                _закрытьInfo = new RepoItemInfo(this, "Закрыть", "?/?/button[@accessiblename='Закрыть']", "?/?/button[@accessiblename='Закрыть']", 30000, null, "1bd70d01-536d-4cfe-9370-a4075fd4dbdf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c7553724-e8ac-42cb-8933-f5a1c41d0403")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c7553724-e8ac-42cb-8933-f5a1c41d0403")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EdZCoord item.
            /// </summary>
            [RepositoryItem("389fe77b-db42-4533-8527-75fc082e7d46")]
            public virtual Ranorex.Text EdZCoord
            {
                get
                {
                    return _edzcoordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EdZCoord item info.
            /// </summary>
            [RepositoryItemInfo("389fe77b-db42-4533-8527-75fc082e7d46")]
            public virtual RepoItemInfo EdZCoordInfo
            {
                get
                {
                    return _edzcoordInfo;
                }
            }

            /// <summary>
            /// The EdYCoord item.
            /// </summary>
            [RepositoryItem("758cf676-9bea-455f-af4e-35a3faba39d1")]
            public virtual Ranorex.Text EdYCoord
            {
                get
                {
                    return _edycoordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EdYCoord item info.
            /// </summary>
            [RepositoryItemInfo("758cf676-9bea-455f-af4e-35a3faba39d1")]
            public virtual RepoItemInfo EdYCoordInfo
            {
                get
                {
                    return _edycoordInfo;
                }
            }

            /// <summary>
            /// The EdXCoord item.
            /// </summary>
            [RepositoryItem("10bb5678-82d1-49c1-a544-9c8b5c5c29f4")]
            public virtual Ranorex.Text EdXCoord
            {
                get
                {
                    return _edxcoordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The EdXCoord item info.
            /// </summary>
            [RepositoryItemInfo("10bb5678-82d1-49c1-a544-9c8b5c5c29f4")]
            public virtual RepoItemInfo EdXCoordInfo
            {
                get
                {
                    return _edxcoordInfo;
                }
            }

            /// <summary>
            /// The ВПлоскостиXY item.
            /// </summary>
            [RepositoryItem("c4f0ddb5-69e4-4e85-8f09-949159db1a0b")]
            public virtual Ranorex.Button ВПлоскостиXY
            {
                get
                {
                    return _вплоскостиxyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ВПлоскостиXY item info.
            /// </summary>
            [RepositoryItemInfo("c4f0ddb5-69e4-4e85-8f09-949159db1a0b")]
            public virtual RepoItemInfo ВПлоскостиXYInfo
            {
                get
                {
                    return _вплоскостиxyInfo;
                }
            }

            /// <summary>
            /// The ВПлоскостиXZ item.
            /// </summary>
            [RepositoryItem("bebbfa94-8f36-4552-b028-598c11519480")]
            public virtual Ranorex.Button ВПлоскостиXZ
            {
                get
                {
                    return _вплоскостиxzInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ВПлоскостиXZ item info.
            /// </summary>
            [RepositoryItemInfo("bebbfa94-8f36-4552-b028-598c11519480")]
            public virtual RepoItemInfo ВПлоскостиXZInfo
            {
                get
                {
                    return _вплоскостиxzInfo;
                }
            }

            /// <summary>
            /// The ВПлоскостиYZ item.
            /// </summary>
            [RepositoryItem("5f4b7aca-1248-4e52-be6a-69f17d797e75")]
            public virtual Ranorex.Button ВПлоскостиYZ
            {
                get
                {
                    return _вплоскостиyzInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ВПлоскостиYZ item info.
            /// </summary>
            [RepositoryItemInfo("5f4b7aca-1248-4e52-be6a-69f17d797e75")]
            public virtual RepoItemInfo ВПлоскостиYZInfo
            {
                get
                {
                    return _вплоскостиyzInfo;
                }
            }

            /// <summary>
            /// The ПланПоXY item.
            /// </summary>
            [RepositoryItem("ece82c9f-c2d2-4d62-ae18-0170de7fa5d8")]
            public virtual Ranorex.Button ПланПоXY
            {
                get
                {
                    return _планпоxyInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ПланПоXY item info.
            /// </summary>
            [RepositoryItemInfo("ece82c9f-c2d2-4d62-ae18-0170de7fa5d8")]
            public virtual RepoItemInfo ПланПоXYInfo
            {
                get
                {
                    return _планпоxyInfo;
                }
            }

            /// <summary>
            /// The Произвольный item.
            /// </summary>
            [RepositoryItem("6166c0e5-b0ec-47f0-b66e-c132a8a2f83e")]
            public virtual Ranorex.Button Произвольный
            {
                get
                {
                    return _произвольныйInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Произвольный item info.
            /// </summary>
            [RepositoryItemInfo("6166c0e5-b0ec-47f0-b66e-c132a8a2f83e")]
            public virtual RepoItemInfo ПроизвольныйInfo
            {
                get
                {
                    return _произвольныйInfo;
                }
            }

            /// <summary>
            /// The Закрыть item.
            /// </summary>
            [RepositoryItem("1bd70d01-536d-4cfe-9370-a4075fd4dbdf")]
            public virtual Ranorex.Button Закрыть
            {
                get
                {
                    return _закрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Закрыть item info.
            /// </summary>
            [RepositoryItemInfo("1bd70d01-536d-4cfe-9370-a4075fd4dbdf")]
            public virtual RepoItemInfo ЗакрытьInfo
            {
                get
                {
                    return _закрытьInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
