///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The StartAUT recording.
    /// </summary>
    [TestModule("dfda3f25-5035-4aea-87c2-dbf20704e594", ModuleType.Recording, 1)]
    public partial class StartAUT : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static StartAUT instance = new StartAUT();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public StartAUT()
        {
            StartAutProcessIDVar = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static StartAUT Instance
        {
            get { return instance; }
        }

#region Variables

        string _StartAutProcessIDVar;

        /// <summary>
        /// Gets or sets the value of variable StartAutProcessIDVar.
        /// </summary>
        [TestVariable("e5c7d423-2353-4c2f-8639-e517f3931d0c")]
        public string StartAutProcessIDVar
        {
            get { return _StartAutProcessIDVar; }
            set { _StartAutProcessIDVar = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Program Files\\Mineframe\\bin\\Geotech_Demo.exe' in normal mode. Return value bound to $StartAutProcessIDVar.", new RecordItemIndex(0));
            StartAutProcessIDVar = ValueConverter.ToString(Host.Local.RunApplication("C:\\Program Files\\Mineframe\\bin\\Geotech_Demo.exe", "", "", false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.Open' at Center.", repo.GEOTECH3D9118616917X64Демонстра.OpenInfo, new RecordItemIndex(1));
            repo.GEOTECH3D9118616917X64Демонстра.Open.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTech3D.ПодземныеГорныеРаботыФрагмент' at Center.", repo.GeoTech3D.ПодземныеГорныеРаботыФрагментInfo, new RecordItemIndex(2));
            repo.GeoTech3D.ПодземныеГорныеРаботыФрагмент.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTech3D.Открыть' at Center.", repo.GeoTech3D.ОткрытьInfo, new RecordItemIndex(3));
            repo.GeoTech3D.Открыть.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'GEOTECH3D9118616917X64Демонстра.Геология' at CenterLeft.", repo.GEOTECH3D9118616917X64Демонстра.ГеологияInfo, new RecordItemIndex(4));
            repo.GEOTECH3D9118616917X64Демонстра.Геология.DoubleClick(Location.CenterLeft);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'GEOTECH3D9118616917X64Демонстра.TreeItem1113410' at Center.", repo.GEOTECH3D9118616917X64Демонстра.TreeItem1113410Info, new RecordItemIndex(5));
            repo.GEOTECH3D9118616917X64Демонстра.TreeItem1113410.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeotechDemo.MenuItem' at Center.", repo.GeotechDemo.MenuItemInfo, new RecordItemIndex(6));
            repo.GeotechDemo.MenuItem.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.MenuItemРазрез' at Center.", repo.GEOTECH3D9118616917X64Демонстра.MenuItemРазрезInfo, new RecordItemIndex(7));
            repo.GEOTECH3D9118616917X64Демонстра.MenuItemРазрез.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeotechDemo.ФормированиеРазрезов' at Center.", repo.GeotechDemo.ФормированиеРазрезовInfo, new RecordItemIndex(8));
            repo.GeotechDemo.ФормированиеРазрезов.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '499' on item 'GeoTech3D1.EdZCoord'.", repo.GeoTech3D1.EdZCoordInfo, new RecordItemIndex(9));
            repo.GeoTech3D1.EdZCoord.Element.SetAttributeValue("Text", "499");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '1417' on item 'GeoTech3D1.EdYCoord'.", repo.GeoTech3D1.EdYCoordInfo, new RecordItemIndex(10));
            repo.GeoTech3D1.EdYCoord.Element.SetAttributeValue("Text", "1417");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '1020' on item 'GeoTech3D1.EdXCoord'.", repo.GeoTech3D1.EdXCoordInfo, new RecordItemIndex(11));
            repo.GeoTech3D1.EdXCoord.Element.SetAttributeValue("Text", "1020");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTech3D1.ВПлоскостиXY' at Center.", repo.GeoTech3D1.ВПлоскостиXYInfo, new RecordItemIndex(12));
            repo.GeoTech3D1.ВПлоскостиXY.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTech3D1.ВПлоскостиXZ' at Center.", repo.GeoTech3D1.ВПлоскостиXZInfo, new RecordItemIndex(13));
            repo.GeoTech3D1.ВПлоскостиXZ.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTech3D1.ВПлоскостиYZ' at Center.", repo.GeoTech3D1.ВПлоскостиYZInfo, new RecordItemIndex(14));
            repo.GeoTech3D1.ВПлоскостиYZ.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTech3D1.ПланПоXY' at Center.", repo.GeoTech3D1.ПланПоXYInfo, new RecordItemIndex(15));
            repo.GeoTech3D1.ПланПоXY.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTech3D1.Произвольный' at Center.", repo.GeoTech3D1.ПроизвольныйInfo, new RecordItemIndex(16));
            repo.GeoTech3D1.Произвольный.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагмент'.", repo.GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагментInfo, new RecordItemIndex(17));
            //Validate.Exists(repo.GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагментInfo);
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагмент' at Center.", repo.GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагментInfo, new RecordItemIndex(18));
            repo.GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагмент.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.Form65280.Z500000' at Center.", repo.GEOTECH3D9118616917X64Демонстра.Form65280.Z500000Info, new RecordItemIndex(19));
            repo.GEOTECH3D9118616917X64Демонстра.Form65280.Z500000.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.Form65280.М100000' at Center.", repo.GEOTECH3D9118616917X64Демонстра.Form65280.М100000Info, new RecordItemIndex(20));
            repo.GEOTECH3D9118616917X64Демонстра.Form65280.М100000.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.Form65280.Р6Plus44000' at Center.", repo.GEOTECH3D9118616917X64Демонстра.Form65280.Р6Plus44000Info, new RecordItemIndex(21));
            repo.GEOTECH3D9118616917X64Демонстра.Form65280.Р6Plus44000.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.Form65280.План' at Center.", repo.GEOTECH3D9118616917X64Демонстра.Form65280.ПланInfo, new RecordItemIndex(22));
            repo.GEOTECH3D9118616917X64Демонстра.Form65280.План.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.Form65280.Сеч1' at Center.", repo.GEOTECH3D9118616917X64Демонстра.Form65280.Сеч1Info, new RecordItemIndex(23));
            repo.GEOTECH3D9118616917X64Демонстра.Form65280.Сеч1.Click();
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Application", "Closing application containing item 'GeoTech3D1'.", repo.GeoTech3D1.SelfInfo, new RecordItemIndex(24));
            //Host.Current.CloseApplication(repo.GeoTech3D1.Self, new Duration(0));
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeoTech3D1.Закрыть' at Center.", repo.GeoTech3D1.ЗакрытьInfo, new RecordItemIndex(25));
            repo.GeoTech3D1.Закрыть.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GEOTECH3D9118616917X64Демонстра.MenuItemРазрез' at Center.", repo.GEOTECH3D9118616917X64Демонстра.MenuItemРазрезInfo, new RecordItemIndex(26));
            repo.GEOTECH3D9118616917X64Демонстра.MenuItemРазрез.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeotechDemo.ЗакрытьУдалитьВсеРазрезы' at Center.", repo.GeotechDemo.ЗакрытьУдалитьВсеРазрезыInfo, new RecordItemIndex(27));
            repo.GeotechDemo.ЗакрытьУдалитьВсеРазрезы.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'GEOTECH3D9118616917X64Демонстра.TreeItem1113410' at Center.", repo.GEOTECH3D9118616917X64Демонстра.TreeItem1113410Info, new RecordItemIndex(28));
            repo.GEOTECH3D9118616917X64Демонстра.TreeItem1113410.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeotechDemo.MenuItem' at Center.", repo.GeotechDemo.MenuItemInfo, new RecordItemIndex(29));
            repo.GeotechDemo.MenuItem.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Right Click item 'GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагмент' at Center.", repo.GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагментInfo, new RecordItemIndex(30));
            repo.GEOTECH3D9118616917X64Демонстра.ПодземныеГорныеРаботыФрагмент.Click(System.Windows.Forms.MouseButtons.Right);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'GeotechDemo.MenuItem' at Center.", repo.GeotechDemo.MenuItemInfo, new RecordItemIndex(31));
            repo.GeotechDemo.MenuItem.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
